## @file
# config.plist configuration file for running macOS on Hyper-V
#
# Copyright (c) 2021, Goldfish64. All rights reserved.
# Copyright (c) 2023, Cory Bennett. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

# This file builds on the existing defaults from OCE-Build and MacHyperVSupport.
# @see https://github.com/Qonfused/OCE-Build/blob/main/base-config.yml
# @see https://github.com/acidanthera/MacHyperVSupport/blob/master/README.md

# Refer to the below resources for more information on sensible defaults:
# - https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
#   (or https://dortania.github.io/docs/latest/Configuration.html)


################################################################################
#                               ACPI related fixes                             #
################################################################################

ACPI:
  Patch:
    # Companion to SSDT-HV-DEV-WS2022
    - Base:                 String  | "\\\\P241"
      Comment:              String  | "_STA to XSTA rename (additional Hyper-V processors)"
      Count:                Number  | 1808
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    # Companion to SSDT-HV-VMBUS
    - Base:                 String  | "_SB.VMOD"
      Comment:              String  | "_HID to XHID rename (Hyper-V VMOD)"
      Count:                Number  | 1
      Find:                 Data    | <5F484944>
      Replace:              Data    | <58484944>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.VMOD.VMBS"
      Comment:              String  | "_HID to XHID rename (Hyper-V VMBus)"
      Count:                Number  | 1
      Find:                 Data    | <5F484944>
      Replace:              Data    | <58484944>
      TableSignature:       Data    | <44534454>
    # Companion to SSDT-HV-DEV
    - Base:                 String  | "_SB.VMOD.TPM2"
      Comment:              String  | "_STA to XSTA rename (Hyper-V TPM)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.NVDR"
      Comment:              String  | "_STA to XSTA rename (Hyper-V NVDIMM)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.EPC"
      Comment:              String  | "_STA to XSTA rename (Hyper-V EPC)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.VMOD.BAT1"
      Comment:              String  | "_STA to XSTA rename (Hyper-V battery)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "\\\\P001"
      Comment:              String  | "_STA to XSTA rename (Hyper-V processors)"
      Count:                Number  | 240
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>

################################################################################
#                           BIOS/firmware related fixes                        #
################################################################################

Booter:
  Quirks:
    AvoidRuntimeDefrag:     Boolean | true
    ProvideCustomSlide:     Boolean | true
    # Required for macOS 10.7 and older
    AllowRelocationBlock:   Boolean | true
    RorceExitBootServices:  Boolean | true
    # Required for macOS 10.6 and older
    RebuildAppleMemoryMap:  Boolean | true

################################################################################
#                                  Boot fixes                                  #
################################################################################

Kernel:
  Quirks:
    ProvideCurrentCpuInfo:  Boolean | true

UEFI:
  Quirks:
    # Required on Windows Server 2019 / Windows 10 and newer
    DisableSecurityPolicy:  Boolean | true

################################################################################
#                                  Kernel fixes                                #
################################################################################

Kernel:
  Block:
    # Required for 32-bit versions of macOS (10.4 and 10.5, and 10.6 in 32-bit mode).
    - Arch:                 String  | "i386"
      Comment:              String  | "Disables EFI runtime services and NVRAM due to Hyper-V UEFI incompatibilities"
      Identifier:           String  | "com.apple.driver.AppleEFIRuntime"
      MaxKernel:            String  | "10.0.0"
      MinKernel:            String  | "8.0.0"
      Strategy:             String  | "Disable"
  Force:
    # On older versions of macOS, the following kernel extensions may need to be Force injected.
    # Refer to the OpenCore Configuration manual for details.
    - Arch:                 String  | "i386"
      BundlePath:           String  | "System/Library/Extensions/IONetworkingFamily.kext"
      ExecutablePath:       String  | "Contents/MacOS/IONetworkingFamily"
      Identifier:           String  | "com.apple.iokit.IONetworkingFamily"
      MaxKernel:            String  | "13.99.99"
      PlistPath:            String  | "Contents/Info.plist"
    - Arch:                 String  | "i386"
      BundlePath:           String  | "System/Library/Extensions/IOSCSIParallelFamily.kext"
      ExecutablePath:       String  | "Contents/MacOS/IOSCSIParallelFamily"
      Identifier:           String  | "com.apple.iokit.IOSCSIParallelFamily"
      MaxKernel:            String  | "9.0.0"
      PlistPath:            String  | "Contents/Info.plist"
  Patch:
    # Disable `_hpet_init`
    - Arch:                 String  | "i386"
      Base:                 String  | "_hpet_init"
      Comment:              String  | "Disables _hpet_init due to no HPET hardware present"
      Count:                Number  | 1
      Identifier:           String  | "kernel"
      MaxKernel:            String  | "9.5.99"
      Replace:              Data    | <C3>
    # Disable `IOHIDDeviceShim::newTransportString()`
    - Arch:                 String  | "i386"
      Base:                 String  | "__ZNK15IOHIDDeviceShim18newTransportStringEv"
      Comment:              String  | "Fix crash in IOHIDDeviceShim::newTransportString() caused by NULL _deviceType"
      Count:                Number  | 1
      Identifier:           String  | "com.apple.iokit.IOHIDFamily"
      MaxKernel:            String  | "9.6.99"
      MinKernel:            String  | "9.5.0"
      Replace:              Data    | <31C0C3>
    # Disable scaling factor for X/Y mouse movement`
    - Arch:                 String  | "i386"
      Base:                 String  | "__ZN16IOHIDEventDriver21handleInterruptReportE12UnsignedWideP18IOMemoryDescriptor15IOHIDReportTypem"
      Comment:              String  | "Workaround for absence of AbsoluteAxisBoundsRemovalPercentage in 10.4"
      Identifier:           String  | "com.apple.iokit.IOHIDFamily"
      Find:                 Data    | <BA1F85EB51>
      MaxKernel:            String  | "8.11.99"
      MinKernel:            String  | "8.0.0"
      Replace:              Data    | <BA00000000>
