## @file
# config.plist configuration file patches for running macOS on Hyper-V
#
# Copyright (c) 2021, Goldfish64. All rights reserved.
# Copyright (c) 2023, Cory Bennett. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
##

# This file builds on the existing defaults from OCE-Build and MacHyperVSupport.
# @see https://github.com/Qonfused/OCE-Build/blob/main/base-config.yml
# @see https://github.com/acidanthera/MacHyperVSupport/blob/master/README.md

# Refer to the below resources for more information on sensible defaults:
# - https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf
#   (or https://dortania.github.io/docs/latest/Configuration.html)


################################################################################
#                               ACPI related fixes                             #
################################################################################

ACPI:
  Patch:
    # Companion to SSDT-HV-DEV-WS2022
    - Base:                 String  | "\\\\P241"
      Comment:              String  | "_STA to XSTA rename (additional Hyper-V processors)"
      Count:                Number  | 1808
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    # Companion to SSDT-HV-VMBUS
    - Base:                 String  | "_SB.VMOD"
      Comment:              String  | "_HID to XHID rename (Hyper-V VMOD)"
      Count:                Number  | 1
      Find:                 Data    | <5F484944>
      Replace:              Data    | <58484944>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.VMOD.VMBS"
      Comment:              String  | "_HID to XHID rename (Hyper-V VMBus)"
      Count:                Number  | 1
      Find:                 Data    | <5F484944>
      Replace:              Data    | <58484944>
      TableSignature:       Data    | <44534454>
    # Companion to SSDT-HV-DEV
    - Base:                 String  | "_SB.VMOD.TPM2"
      Comment:              String  | "_STA to XSTA rename (Hyper-V TPM)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.NVDR"
      Comment:              String  | "_STA to XSTA rename (Hyper-V NVDIMM)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.EPC"
      Comment:              String  | "_STA to XSTA rename (Hyper-V EPC)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "_SB.VMOD.BAT1"
      Comment:              String  | "_STA to XSTA rename (Hyper-V battery)"
      Count:                Number  | 1
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>
    - Base:                 String  | "\\\\P001"
      Comment:              String  | "_STA to XSTA rename (Hyper-V processors)"
      Count:                Number  | 240
      Find:                 Data    | <5F535441>
      Replace:              Data    | <58535441>
      TableSignature:       Data    | <44534454>

################################################################################
#                           BIOS/firmware related fixes                        #
################################################################################

Booter:
  Quirks:
    AvoidRuntimeDefrag:     Boolean | true
    ProvideCustomSlide:     Boolean | true

################################################################################
#                                  Boot fixes                                  #
################################################################################

Kernel:
  Quirks:
    # Provides the correct TSC and FSB values to the kernel, as well as disables
    # CPU topology validation (10.8+)
    ProvideCurrentCpuInfo:  Boolean | true

UEFI:
  APFS:
    # Disables minimum APFS version for macOS Catalina and earlier boot entries.
    MinDate:                Number  | -1
    MinVersion:             Number  | -1
  Output:
    # Sets proper display scaling for boot picker + debug logging.
    UIScale:                Number  | -1
  Quirks:
    # Required on Windows Server 2019 / Windows 10 and newer
    DisableSecurityPolicy:  Boolean | true

################################################################################
#                             Security related fixes                           #
################################################################################

Misc:
  Security:
    # Allows setting a default boot entries when holding the CTRL key.
    AllowSetDefault:        Boolean | true
    # Allows all bootable parition types to show in the boot picker.
    # - https://dortania.github.io/OpenCore-Post-Install/universal/security/scanpolicy.html
    ScanPolicy:             Number  | 0
    # Apple Secure Boot hardware model and policy
    # - Possible values include:
    #   - Disabled: No model, Secure Boot will be disabled.
    #   - Default: Currently set to x86legacy
    # - @see https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel
    SecureBootModel:        String  | "Disabled"
    # OpenCore vaulting configuration (optional=no vault enforced, insecure)
    # - @see https://dortania.github.io/OpenCore-Post-Install/universal/security/vault.html
    Vault:                  String  | "Optional"
NVRAM:
  Add:
    7C436110-AB2A-4BBB-A880-FE41995C9F82:
      # Enables System Integrity Protection (SIP) setting in macOS.
      # - Possible values include:
      #   - 00000000: Default (enabled)
      #   - 03000000: Disables Kext signing and filesystem restrictions
      #   - 67000000: Disables all SIP protections
      #   - FF030000: Disables all flags in macOS High Sierra
      #   - FF070000: Disables all flags in macOS Mojave and macOS Catalina
      #   - FF0F0000: Disables all flags in macOS Big Sur
      # - @see https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip
      csr-active-config:    Data    | <00000000>
